main:
  host: 0.0.0.0
  port: 8080
slack:
  token: <slack token>
  channel: <slack channel>
jira:
  token: <jira token>
pagerduty:
  token: <pagerduty token>
  subdomain: <your subdomain on pagerduty>
  timezone: Moscow
duty-command:
  token: <slack auth token for duty command>
  schedule-ids:
    - <your schedule id>
  cache-ttl: 5m
  daily-message-time: 09:47
timelogs-command:
  token: <slack auth token for timelogs command>
  minimum-time-logged: 6h
  cache-ttl: 5m
  daily-message-time: 09:47
  team:
  - name: "John Doe"
    jira-login: johndoe
    slack-login: john.doe